"""Chesskers self-play training — single file, upload with the two
.pt checkpoints (created on first run) and nothing else.

    !pip install torch numpy
    !python train.py --games 100

chess_net always plays the chess army and only learns from chess-side
trajectories; checkers_net is the same for checkers. They never swap
sides, never share weights or gradients — one optimizer each.

Actor-critic self-play (policy gradient + a learned value head), no
search. Reward is terminal-only: +1 / -1 / 0, no shaping. A shorter
winning game is preferred through the discount factor (--gamma) on
that side's own move sequence, not a second reward term.

Checkpoints (chess_net.pt / checkers_net.pt) are written atomically —
a temp file, then an atomic rename — after every --checkpoint-every
games (default: every game). If the runtime dies mid-game or
mid-write, the file on disk is still exactly the last FULLY
COMPLETED game's weights, never a half-written file, and the next
run auto-resumes from it (each checkpoint also carries a persistent
games-trained counter, so game counts keep incrementing correctly
across separate Colab sessions instead of restarting at 1). Only
model weights are checkpointed, not optimizer momentum, so a resume
is not bit-identical to an uninterrupted run, but is always valid.

Progress prints as one self-overwriting status line per game (not a
line per game — this can be thousands of games) plus a permanent
log line every --log-every games, so a crash leaves a short, readable
trail instead of a huge scrollback.

RuleConfig here is plain defaults, matching the deployed server's
default ACTIVE_CONFIG (engine/config.py: the whole point of the
config hash is to make a rules mismatch loud, not silent — check the
printed hash against the server's GET /api/config if it's been
changed from defaults).

Auto-generated by scripts/build_bot_training.py from engine/*.py +
scripts/train_logic.py. Do not hand-edit — re-run that script after
changing either source."""
from __future__ import annotations

import argparse
import csv
import datetime
import hashlib
import json
import numpy as np
import os
import random
import sys
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
from dataclasses import asdict, dataclass
from enum import IntEnum
from typing import Optional

# ==== engine/config.py ====
"""RuleConfig: the single source of truth for every rule variant. See spec section 7.1."""

@dataclass(frozen=True)
class RuleConfig:
    """Every rule variant this game supports (spec 7.1). Immutable, embedded
    in every serialized state and every self-play/match record, so a model or
    client can never silently disagree with the server about the ruleset."""
    mandatory_capture: bool = True
    maximal_capture: bool = False
    flying_kings: bool = False
    layout: str = 'standard_24v16'
    first_mover: str = 'random'
    fifty_move_plies: int = 100
    promotion_ends_jump_chain: bool = True
    king_capture_immunity: bool = False
    "Was a temporary experiment flag, now the live default (2026-08-13):\n    checkers went 0-1015 while True. True = legacy behaviour, chess's king\n    protected two ways checkers gets no equivalent for — legal.py filters out\n    any chess move leaving the king attacked (info checkers never gets about\n    its own pieces), and checkers_gen.py refuses to ever generate a jump that\n    captures a K square at all. False (current default) = symmetric: chess\n    can walk into an attack same as checkers can lose a piece, and a checkers\n    jump onto/through K is a real, game-ending capture."

    def config_hash(self) -> str:
        """Short stable hash identifying this exact rule set (spec 7.5)."""
        payload = repr(sorted(asdict(self).items())).encode('utf-8')
        return hashlib.sha256(payload).hexdigest()[:10]

    def to_json(self) -> dict:
        return asdict(self)

    @staticmethod
    def from_json(d: dict) -> 'RuleConfig':
        return RuleConfig(**d)


# ==== engine/moves.py ====
"""Packed integer move encoding. Spec section 7.3.

bits  0-5   from square (0-63)
bits  6-11  to square (0-63)
bits 12-15  move type
"""

class MoveType(IntEnum):
    """The 16 move kinds a packed move can encode (fits the 4-bit type field)."""
    QUIET = 0
    CAPTURE = 1
    DOUBLE_PUSH = 2
    KING_CASTLE = 3
    QUEEN_CASTLE = 4
    EP_CAPTURE = 5
    PROMO_N = 6
    PROMO_B = 7
    PROMO_R = 8
    PROMO_Q = 9
    PROMO_CAP_N = 10
    PROMO_CAP_B = 11
    PROMO_CAP_R = 12
    PROMO_CAP_Q = 13
    CHECKER_STEP = 14
    CHECKER_JUMP = 15
PROMO_PIECE = {MoveType.PROMO_N: 'N', MoveType.PROMO_B: 'B', MoveType.PROMO_R: 'R', MoveType.PROMO_Q: 'Q', MoveType.PROMO_CAP_N: 'N', MoveType.PROMO_CAP_B: 'B', MoveType.PROMO_CAP_R: 'R', MoveType.PROMO_CAP_Q: 'Q'}
PROMO_TYPES = {'N': (MoveType.PROMO_N, MoveType.PROMO_CAP_N), 'B': (MoveType.PROMO_B, MoveType.PROMO_CAP_B), 'R': (MoveType.PROMO_R, MoveType.PROMO_CAP_R), 'Q': (MoveType.PROMO_Q, MoveType.PROMO_CAP_Q)}
IS_PROMO = {MoveType.PROMO_N, MoveType.PROMO_B, MoveType.PROMO_R, MoveType.PROMO_Q, MoveType.PROMO_CAP_N, MoveType.PROMO_CAP_B, MoveType.PROMO_CAP_R, MoveType.PROMO_CAP_Q}
IS_CAPTURE = {MoveType.CAPTURE, MoveType.EP_CAPTURE, MoveType.CHECKER_JUMP, MoveType.PROMO_CAP_N, MoveType.PROMO_CAP_B, MoveType.PROMO_CAP_R, MoveType.PROMO_CAP_Q}

def encode(frm: int, to: int, mtype: MoveType) -> int:
    """Packs a move into a single int (spec 7.3)."""
    return frm & 63 | (to & 63) << 6 | (int(mtype) & 15) << 12

def decode(mv: int) -> tuple[int, int, MoveType]:
    """Unpacks a move int into (from_square, to_square, MoveType)."""
    frm = mv & 63
    to = mv >> 6 & 63
    mtype = MoveType(mv >> 12 & 15)
    return (frm, to, mtype)
SQUARE_NAMES = [f"{chr(ord('a') + f)}{r + 1}" for r in range(8) for f in range(8)]
NAME_TO_SQUARE = {name: i for i, name in enumerate(SQUARE_NAMES)}

def square_name(sq: int) -> str:
    """0-63 square index -> algebraic name, e.g. 0 -> 'a1'."""
    return SQUARE_NAMES[sq]

def square_from_name(name: str) -> int:
    """Algebraic square name -> 0-63 index, e.g. 'a1' -> 0."""
    return NAME_TO_SQUARE[name]

def move_to_uci(mv: int) -> str:
    """Packed move -> UCI-style string (e.g. 'e2e4', 'e1g1' for castling, 'a7a8q')."""
    frm, to, mtype = decode(mv)
    s = square_name(frm) + square_name(to)
    if mtype in PROMO_PIECE:
        s += PROMO_PIECE[mtype].lower()
    return s


# ==== engine/board.py ====
"""Position: board state, layouts, make/unmake, Zobrist hashing. Spec section 7.2."""
EMPTY = '.'
WHITE_PIECES = set('PNBRQK')
BLACK_CHESS_PIECES = set('pnbrqk')
CHECKER_PIECES = set('cC')
ROOK_CASTLE_RIGHT = {0: 'Q', 7: 'K', 56: 'q', 63: 'k'}
KING_START = {'w': 4, 'b': 60}
ROOK_START = {'w': (0, 7), 'b': (56, 63)}

class Side(IntEnum):
    """Which army is to move: the chess army or the checkers army."""
    CHESS = 0
    CHECKERS = 1

class Result(IntEnum):
    """Terminal outcome of a game (spec section 5)."""
    CHESS_WIN = 0
    CHECKERS_WIN = 1
    DRAW = 2

def sq_rf(sq: int) -> tuple[int, int]:
    """0-63 square index -> (rank_idx, file_idx)."""
    return (sq // 8, sq % 8)

def rf_sq(r: int, f: int) -> Optional[int]:
    """(rank_idx, file_idx) -> 0-63 square index, or None if off the board."""
    if 0 <= r < 8 and 0 <= f < 8:
        return r * 8 + f
    return None
_PIECE_CHARS = 'PNBRQKpnbrqkcC'
_rng = random.Random(806485)
ZOBRIST_PIECE = {ch: [_rng.getrandbits(64) for _ in range(64)] for ch in _PIECE_CHARS}
ZOBRIST_SIDE = _rng.getrandbits(64)
ZOBRIST_CASTLING = {ch: _rng.getrandbits(64) for ch in 'KQkq'}
ZOBRIST_EP_FILE = [_rng.getrandbits(64) for _ in range(8)]
ZOBRIST_JUMP_FROM = [_rng.getrandbits(64) for _ in range(64)]

def _layout_standard_24v16() -> list[str]:
    board = [EMPTY] * 64
    back = 'RNBQKBNR'
    for f in range(8):
        board[rf_sq(0, f)] = back[f]
        board[rf_sq(1, f)] = 'P'
    for r in (5, 6, 7):
        for f in range(8):
            board[rf_sq(r, f)] = 'c'
    return board

def _layout_light_16v16() -> list[str]:
    board = [EMPTY] * 64
    back = 'RNBQKBNR'
    for f in range(8):
        board[rf_sq(0, f)] = back[f]
        board[rf_sq(1, f)] = 'P'
    for r in (6, 7):
        for f in range(8):
            board[rf_sq(r, f)] = 'c'
    return board

def _layout_kings_12v16() -> list[str]:
    board = [EMPTY] * 64
    back = 'RNBQKBNR'
    for f in range(8):
        board[rf_sq(0, f)] = back[f]
        board[rf_sq(1, f)] = 'P'
    for r in (6, 7):
        for f in range(8):
            board[rf_sq(r, f)] = 'C'
    return board
LAYOUTS = {'standard_24v16': _layout_standard_24v16, 'light_16v16': _layout_light_16v16, 'kings_12v16': _layout_kings_12v16}

def _layout_chess_only() -> list[str]:
    board = [EMPTY] * 64
    back = 'RNBQKBNR'
    for f in range(8):
        board[rf_sq(0, f)] = back[f]
        board[rf_sq(1, f)] = 'P'
        board[rf_sq(6, f)] = 'p'
        board[rf_sq(7, f)] = back[f].lower()
    return board
STANDARD_FEN = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'

def parse_fen(fen: str) -> tuple[list[str], str, set, Optional[int], int, int]:
    """Parse a standard chess FEN into engine-internal pieces. Used only by chess_only mode."""
    parts = fen.strip().split()
    board_part, side_part, castle_part, ep_part = (parts[0], parts[1], parts[2], parts[3])
    halfmove = int(parts[4]) if len(parts) > 4 else 0
    fullmove = int(parts[5]) if len(parts) > 5 else 1
    board = [EMPTY] * 64
    ranks = board_part.split('/')
    for i, rank_str in enumerate(ranks):
        r = 7 - i
        f = 0
        for ch in rank_str:
            if ch.isdigit():
                f += int(ch)
            else:
                board[rf_sq(r, f)] = ch
                f += 1
    castling = set((c for c in castle_part if c in 'KQkq'))
    ep_square = None
    if ep_part != '-':
        file_idx = ord(ep_part[0]) - ord('a')
        rank_idx = int(ep_part[1]) - 1
        ep_square = rf_sq(rank_idx, file_idx)
    side = 'w' if side_part == 'w' else 'b'
    return (board, side, castling, ep_square, halfmove, fullmove)

@dataclass
class Undo:
    """Everything Position.make() changed, so unmake() can restore it exactly."""
    mv: int
    moved_piece: str
    frm: int
    to: int
    mtype: MoveType
    captured_piece: str
    captured_square: Optional[int]
    prev_castling: frozenset
    prev_ep_square: Optional[int]
    prev_halfmove_clock: int
    prev_fullmove_number: int
    prev_jump_from: Optional[int]
    prev_side_to_move: Side
    prev_key: int
    rook_frm: Optional[int] = None
    rook_to: Optional[int] = None
    promoted: bool = False

class Position:
    """Board state, side to move, and all rule-relevant state (spec 7.2)."""

    def __init__(self, config: RuleConfig, layout: Optional[str]=None):
        self.config = config
        self.mode = 'hybrid'
        layout_name = layout or config.layout
        if layout_name == 'chess_only_test':
            self.mode = 'chess_only'
            self.board = _layout_chess_only()
            self.chess_color = 'w'
            self.castling = {'K', 'Q', 'k', 'q'}
        else:
            self.board = LAYOUTS[layout_name]()
            self.chess_color = 'w'
            self.castling = {'K', 'Q'}
        self.side_to_move = self._initial_side()
        self.ep_square: Optional[int] = None
        self.halfmove_clock = 0
        self.fullmove_number = 1
        self.jump_from: Optional[int] = None
        self.history: list[int] = []
        self._key = self._compute_key()
        self.history.append(self._key)

    def _initial_side(self) -> Side:
        fm = self.config.first_mover
        if fm == 'chess':
            return Side.CHESS
        if fm == 'checkers':
            return Side.CHECKERS
        return Side.CHESS if random.random() < 0.5 else Side.CHECKERS

    @classmethod
    def from_fen(cls, fen: str, config: RuleConfig) -> 'Position':
        """Standard chess FEN -> chess_only-mode Position (perft/differential test harness only, spec 3.4/9.1)."""
        pos = cls.__new__(cls)
        pos.config = config
        pos.mode = 'chess_only'
        board, side, castling, ep_square, halfmove, fullmove = parse_fen(fen)
        pos.board = board
        pos.chess_color = side
        pos.castling = castling
        pos.side_to_move = Side.CHESS if side == 'w' else Side.CHECKERS
        pos.ep_square = ep_square
        pos.halfmove_clock = halfmove
        pos.fullmove_number = fullmove
        pos.jump_from = None
        pos.history = []
        pos._key = pos._compute_key()
        pos.history.append(pos._key)
        return pos

    def _compute_key(self) -> int:
        k = 0
        for sq, ch in enumerate(self.board):
            if ch != EMPTY:
                k ^= ZOBRIST_PIECE[ch][sq]
        if self.side_to_move == Side.CHECKERS:
            k ^= ZOBRIST_SIDE
        for ch in self.castling:
            k ^= ZOBRIST_CASTLING[ch]
        if self.ep_square is not None:
            k ^= ZOBRIST_EP_FILE[self.ep_square % 8]
        if self.jump_from is not None:
            k ^= ZOBRIST_JUMP_FROM[self.jump_from]
        return k

    def key(self) -> int:
        """Zobrist hash of the full position: board + side + castling + ep + jump_from."""
        return self._key

    def legal_moves(self) -> list[int]:
        """All legal moves for the side to move, as packed ints (spec 7.3)."""
        return legal_moves(self)

    def result(self):
        """Terminal result of the game, or None if it continues (spec 5)."""
        return result(self)

    def copy(self) -> 'Position':
        """Deep-enough copy: board, config reference, and all state fields."""
        pos = Position.__new__(Position)
        pos.config = self.config
        pos.mode = self.mode
        pos.board = list(self.board)
        pos.chess_color = self.chess_color
        pos.castling = set(self.castling)
        pos.side_to_move = self.side_to_move
        pos.ep_square = self.ep_square
        pos.halfmove_clock = self.halfmove_clock
        pos.fullmove_number = self.fullmove_number
        pos.jump_from = self.jump_from
        pos.history = list(self.history)
        pos._key = self._key
        return pos

    def to_planes(self, legal=None):
        """NN input tensor, shape (planes.NUM_PLANES, 8, 8) float32 (spec 7.6).
        `legal` lets a caller that already ran legal_moves() this ply (e.g.
        self_play_game) hand it in instead of making to_planes() recompute
        it for the mobility-map planes; omit it and to_planes() computes its
        own via engine.legal.legal_moves."""
        return to_planes(self, legal=legal)

    def make(self, mv: int) -> Undo:
        """Applies a packed move in place and returns an Undo to reverse it exactly (spec 7.2)."""
        frm, to, mtype = decode(mv)
        moved = self.board[frm]
        captured = EMPTY
        captured_square = None
        undo = Undo(mv=mv, moved_piece=moved, frm=frm, to=to, mtype=mtype, captured_piece=EMPTY, captured_square=None, prev_castling=frozenset(self.castling), prev_ep_square=self.ep_square, prev_halfmove_clock=self.halfmove_clock, prev_fullmove_number=self.fullmove_number, prev_jump_from=self.jump_from, prev_side_to_move=self.side_to_move, prev_key=self._key)
        irreversible = False
        new_ep_square = None
        if mtype == MoveType.CHECKER_STEP:
            self.board[to] = moved
            self.board[frm] = EMPTY
            irreversible = True
            self._maybe_promote_checker(to)
        elif mtype == MoveType.CHECKER_JUMP:
            cap_sq = self._find_captured_between(frm, to)
            captured = self.board[cap_sq]
            captured_square = cap_sq
            self.board[cap_sq] = EMPTY
            self.board[to] = moved
            self.board[frm] = EMPTY
            irreversible = True
            promoted = self._maybe_promote_checker(to)
            undo.promoted = promoted
            if promoted and self.config.promotion_ends_jump_chain:
                self.jump_from = None
                self.side_to_move = Side.CHESS
            else:
                further = self._checker_jumps_from(to)
                if further:
                    self.jump_from = to
                else:
                    self.jump_from = None
                    self.side_to_move = Side.CHESS
        elif mtype in (MoveType.KING_CASTLE, MoveType.QUEEN_CASTLE):
            self.board[to] = moved
            self.board[frm] = EMPTY
            r = frm // 8
            if mtype == MoveType.KING_CASTLE:
                rook_frm, rook_to = (rf_sq(r, 7), rf_sq(r, 5))
            else:
                rook_frm, rook_to = (rf_sq(r, 0), rf_sq(r, 3))
            self.board[rook_to] = self.board[rook_frm]
            self.board[rook_frm] = EMPTY
            undo.rook_frm, undo.rook_to = (rook_frm, rook_to)
            self._clear_castling_rights(moved)
        elif mtype == MoveType.EP_CAPTURE:
            direction = -8 if moved.isupper() else 8
            cap_sq = to + direction
            captured = self.board[cap_sq]
            captured_square = cap_sq
            self.board[cap_sq] = EMPTY
            self.board[to] = moved
            self.board[frm] = EMPTY
            irreversible = True
        elif mtype == MoveType.DOUBLE_PUSH:
            self.board[to] = moved
            self.board[frm] = EMPTY
            new_ep_square = (frm + to) // 2
            irreversible = True
        elif mtype in IS_PROMO:
            if mtype in IS_CAPTURE:
                captured = self.board[to]
                captured_square = to
            promo_char = PROMO_PIECE[mtype]
            self.board[to] = promo_char if moved.isupper() else promo_char.lower()
            self.board[frm] = EMPTY
            irreversible = True
        elif mtype == MoveType.CAPTURE:
            captured = self.board[to]
            captured_square = to
            self.board[to] = moved
            self.board[frm] = EMPTY
            irreversible = True
        else:
            self.board[to] = moved
            self.board[frm] = EMPTY
            if moved.upper() == 'P':
                irreversible = True
        undo.captured_piece = captured
        undo.captured_square = captured_square
        if mtype != MoveType.CHECKER_JUMP:
            if moved.upper() in ('K', 'R') or ROOK_CASTLE_RIGHT.get(frm) or ROOK_CASTLE_RIGHT.get(to):
                self._clear_castling_rights(moved, frm=frm, to=to)
            self.ep_square = new_ep_square
            self.side_to_move = Side.CHECKERS if self.side_to_move == Side.CHESS else Side.CHESS
        if captured != EMPTY:
            irreversible = True
        if irreversible:
            self.halfmove_clock = 0
        else:
            self.halfmove_clock += 1
        if self.side_to_move == Side.CHESS and undo.prev_side_to_move == Side.CHECKERS:
            self.fullmove_number += 1
        self._key = self._compute_key()
        self.history.append(self._key)
        return undo

    def unmake(self, undo: Undo) -> None:
        """Reverses exactly one make() call, restoring the position (spec 7.2)."""
        self.history.pop()
        mtype = undo.mtype
        frm, to = (undo.frm, undo.to)
        if mtype == MoveType.CHECKER_STEP:
            self.board[frm] = undo.moved_piece
            self.board[to] = EMPTY
        elif mtype == MoveType.CHECKER_JUMP:
            self.board[frm] = undo.moved_piece
            self.board[to] = EMPTY
            self.board[undo.captured_square] = undo.captured_piece
        elif mtype in (MoveType.KING_CASTLE, MoveType.QUEEN_CASTLE):
            self.board[frm] = undo.moved_piece
            self.board[to] = EMPTY
            self.board[undo.rook_frm] = self.board[undo.rook_to]
            self.board[undo.rook_to] = EMPTY
        elif mtype == MoveType.EP_CAPTURE:
            self.board[frm] = undo.moved_piece
            self.board[to] = EMPTY
            self.board[undo.captured_square] = undo.captured_piece
        elif mtype in IS_PROMO:
            self.board[frm] = undo.moved_piece
            self.board[to] = undo.captured_piece if mtype in IS_CAPTURE else EMPTY
        elif mtype == MoveType.CAPTURE:
            self.board[frm] = undo.moved_piece
            self.board[to] = undo.captured_piece
        else:
            self.board[frm] = undo.moved_piece
            self.board[to] = EMPTY
        self.castling = set(undo.prev_castling)
        self.ep_square = undo.prev_ep_square
        self.halfmove_clock = undo.prev_halfmove_clock
        self.fullmove_number = undo.prev_fullmove_number
        self.jump_from = undo.prev_jump_from
        self.side_to_move = undo.prev_side_to_move
        self._key = undo.prev_key

    def _clear_castling_rights(self, moved_piece: str, frm: Optional[int]=None, to: Optional[int]=None) -> None:
        if moved_piece == 'K':
            self.castling -= {'K', 'Q'}
        elif moved_piece == 'k':
            self.castling -= {'k', 'q'}
        for sq in (frm, to):
            right = ROOK_CASTLE_RIGHT.get(sq)
            if right:
                self.castling.discard(right)

    def _maybe_promote_checker(self, sq: int) -> bool:
        """Man reaching rank 1 promotes to king. Spec 3.2 promotion rule."""
        if self.board[sq] == 'c' and sq // 8 == 0:
            self.board[sq] = 'C'
            return True
        return False

    def _find_captured_between(self, frm: int, to: int) -> int:
        r0, f0 = sq_rf(frm)
        r1, f1 = sq_rf(to)
        dr = 1 if r1 > r0 else -1
        df = 1 if f1 > f0 else -1
        r, f = (r0 + dr, f0 + df)
        found = None
        while (r, f) != (r1, f1):
            sq = rf_sq(r, f)
            if self.board[sq] != EMPTY:
                found = sq
            r += dr
            f += df
        return found

    def _checker_jumps_from(self, sq: int) -> list[tuple[int, int]]:
        """Pseudo-legal jump destinations for the checker piece at sq (any distance if flying)."""
        piece = self.board[sq]
        if piece not in CHECKER_PIECES:
            return []
        is_king = piece == 'C'
        r0, f0 = sq_rf(sq)
        results = []
        directions = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
        if not is_king:
            directions = [(-1, 1), (-1, -1)]
        for dr, df in directions:
            if is_king and self.config.flying_kings:
                r, f = (r0 + dr, f0 + df)
                path_clear = []
                while True:
                    mid = rf_sq(r, f)
                    if mid is None:
                        break
                    if self.board[mid] == EMPTY:
                        path_clear.append(mid)
                        r += dr
                        f += df
                        continue
                    target_piece = self.board[mid]
                    king_exempt = target_piece == 'K' and self.config.king_capture_immunity
                    if target_piece not in CHECKER_PIECES and (not king_exempt):
                        lr, lf = (r + dr, f + df)
                        while True:
                            land = rf_sq(lr, lf)
                            if land is None or self.board[land] != EMPTY:
                                break
                            results.append((mid, land))
                            lr += dr
                            lf += df
                    break
            else:
                mid = rf_sq(r0 + dr, f0 + df)
                if mid is None:
                    continue
                mid_piece = self.board[mid]
                king_exempt = mid_piece == 'K' and self.config.king_capture_immunity
                if mid_piece == EMPTY or king_exempt or mid_piece in CHECKER_PIECES:
                    continue
                land = rf_sq(r0 + 2 * dr, f0 + 2 * df)
                if land is not None and self.board[land] == EMPTY:
                    results.append((mid, land))
        return results

    def repetition_count(self) -> int:
        """How many times the current position's key has occurred in this game's history."""
        return self.history.count(self._key)

    def to_fen(self) -> str:
        """Standard chess FEN export. Only meaningful in chess_only mode."""
        rows = []
        for r in range(7, -1, -1):
            row = ''
            empties = 0
            for f in range(8):
                ch = self.board[rf_sq(r, f)]
                if ch == EMPTY:
                    empties += 1
                else:
                    if empties:
                        row += str(empties)
                        empties = 0
                    row += ch
            if empties:
                row += str(empties)
            rows.append(row)
        board_part = '/'.join(rows)
        side_part = 'w' if self.side_to_move == Side.CHESS else 'b'
        castle_part = ''.join((c for c in 'KQkq' if c in self.castling)) or '-'
        ep_part = '-'
        if self.ep_square is not None:
            r, f = sq_rf(self.ep_square)
            ep_part = f"{chr(ord('a') + f)}{r + 1}"
        return f'{board_part} {side_part} {castle_part} {ep_part} {self.halfmove_clock} {self.fullmove_number}'


# ==== engine/attacks.py ====
"""Attack detection. Spec section 3.5 (is_attacked_by_checkers) plus a generic
standard-chess attack function used only by the chess-only perft/differential mode.
"""
DIAG4 = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
KNIGHT_OFFS = [(1, 2), (2, 1), (2, -1), (1, -2), (-1, -2), (-2, -1), (-2, 1), (-1, 2)]
ORTHO4 = [(1, 0), (-1, 0), (0, 1), (0, -1)]

def checkers_attacking(position: Position, square: int) -> list[int]:
    """Spec 3.5: source square(s) of every checker that can jump X (`square`)
    and land empty. Direction d = (dr, df) is the direction of travel
    S -> X -> L. Men only travel with dr == -1 (toward rank 1, spec 3.2).
    Kings travel any of the four diagonals; flying kings (config) may source
    the jump from any distance along the diagonal provided the path is clear
    (spec 3.2). Empty list == not attacked; is_attacked_by_checkers is just
    bool(this)."""
    board = position.board
    flying = position.config.flying_kings
    r1, f1 = sq_rf(square)
    sources = []
    for dr, df in DIAG4:
        land = rf_sq(r1 + dr, f1 + df)
        if land is None or board[land] != EMPTY:
            continue
        r, f = (r1 - dr, f1 - df)
        first = True
        while True:
            s = rf_sq(r, f)
            if s is None:
                break
            piece = board[s]
            if piece == EMPTY:
                if not flying:
                    break
                r -= dr
                f -= df
                first = False
                continue
            if piece == 'c' and first and (dr == -1):
                sources.append(s)
            elif piece == 'C' and (first or flying):
                sources.append(s)
            break
    return sources

def is_attacked_by_checkers(position: Position, square: int) -> bool:
    """Spec 3.5: X is attacked if a checker on S can jump it and land empty."""
    return bool(checkers_attacking(position, square))

def _find_king(board: list[str], king_char: str) -> int | None:
    for sq, ch in enumerate(board):
        if ch == king_char:
            return sq
    return None

def is_square_attacked_by_chess(position: Position, square: int, by_white: bool) -> bool:
    """Standard FIDE attack detection, used only in chess_only mode (perft/differential)."""
    board = position.board
    r1, f1 = sq_rf(square)
    pawn, knight, bishop, rook, queen, king = 'PNBRQK' if by_white else 'pnbrqk'
    pawn_dr = -1 if by_white else 1
    for df in (1, -1):
        s = rf_sq(r1 + pawn_dr, f1 + df)
        if s is not None and board[s] == pawn:
            return True
    for dr, df in KNIGHT_OFFS:
        s = rf_sq(r1 + dr, f1 + df)
        if s is not None and board[s] == knight:
            return True
    for dr, df in DIAG4:
        s = rf_sq(r1 + dr, f1 + df)
        if s is not None and board[s] == king:
            return True
    for dr, df in ORTHO4:
        s = rf_sq(r1 + dr, f1 + df)
        if s is not None and board[s] == king:
            return True
    for dr, df in DIAG4:
        r, f = (r1 + dr, f1 + df)
        while True:
            s = rf_sq(r, f)
            if s is None:
                break
            piece = board[s]
            if piece == EMPTY:
                r += dr
                f += df
                continue
            if piece == bishop or piece == queen:
                return True
            break
    for dr, df in ORTHO4:
        r, f = (r1 + dr, f1 + df)
        while True:
            s = rf_sq(r, f)
            if s is None:
                break
            piece = board[s]
            if piece == EMPTY:
                r += dr
                f += df
                continue
            if piece == rook or piece == queen:
                return True
            break
    return False


# ==== engine/chess_gen.py ====
"""Pseudo-legal chess move generation. Spec section 3.1.

Generic over colour so it can serve both the real game (white/CHESS side only)
and the chess-only perft/differential test mode (both colours).
"""
KNIGHT_OFFS = [(1, 2), (2, 1), (2, -1), (1, -2), (-1, -2), (-2, -1), (-2, 1), (-1, 2)]
DIAG4 = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
ORTHO4 = [(1, 0), (-1, 0), (0, 1), (0, -1)]
KING8 = DIAG4 + ORTHO4

def _own_enemy_sets(color: str, chess_only: bool) -> tuple[set, set]:
    if color == 'w':
        own = WHITE_PIECES
        enemy = (BLACK_CHESS_PIECES if chess_only else set()) | CHECKER_PIECES
    else:
        own = BLACK_CHESS_PIECES
        enemy = WHITE_PIECES | (CHECKER_PIECES if not chess_only else set())
    return (own, enemy)

def pseudo_legal_chess_moves(position: Position, color: str) -> list[int]:
    """All pseudo-legal moves for the chess pieces of `color` ('w' or 'b')."""
    board = position.board
    chess_only = position.mode == 'chess_only'
    own, enemy = _own_enemy_sets(color, chess_only)
    moves: list[int] = []
    forward = 1 if color == 'w' else -1
    start_rank = 1 if color == 'w' else 6
    promo_rank = 7 if color == 'w' else 0
    pawn_char = 'P' if color == 'w' else 'p'
    knight_char = 'N' if color == 'w' else 'n'
    bishop_char = 'B' if color == 'w' else 'b'
    rook_char = 'R' if color == 'w' else 'r'
    queen_char = 'Q' if color == 'w' else 'q'
    king_char = 'K' if color == 'w' else 'k'
    for sq in range(64):
        piece = board[sq]
        if piece == EMPTY or piece not in own:
            continue
        r, f = sq_rf(sq)
        if piece == pawn_char:
            one = rf_sq(r + forward, f)
            if one is not None and board[one] == EMPTY:
                if r + forward == promo_rank:
                    for mt in (MoveType.PROMO_N, MoveType.PROMO_B, MoveType.PROMO_R, MoveType.PROMO_Q):
                        moves.append(encode(sq, one, mt))
                else:
                    moves.append(encode(sq, one, MoveType.QUIET))
                    if r == start_rank:
                        two = rf_sq(r + 2 * forward, f)
                        if two is not None and board[two] == EMPTY:
                            moves.append(encode(sq, two, MoveType.DOUBLE_PUSH))
            for df in (-1, 1):
                cap = rf_sq(r + forward, f + df)
                if cap is None:
                    continue
                if board[cap] in enemy:
                    if r + forward == promo_rank:
                        for mt in (MoveType.PROMO_CAP_N, MoveType.PROMO_CAP_B, MoveType.PROMO_CAP_R, MoveType.PROMO_CAP_Q):
                            moves.append(encode(sq, cap, mt))
                    else:
                        moves.append(encode(sq, cap, MoveType.CAPTURE))
                elif position.ep_square is not None and cap == position.ep_square:
                    moves.append(encode(sq, cap, MoveType.EP_CAPTURE))
        elif piece == knight_char:
            for dr, df in KNIGHT_OFFS:
                to = rf_sq(r + dr, f + df)
                if to is None or board[to] in own:
                    continue
                mt = MoveType.CAPTURE if board[to] in enemy else MoveType.QUIET
                moves.append(encode(sq, to, mt))
        elif piece == king_char:
            for dr, df in KING8:
                to = rf_sq(r + dr, f + df)
                if to is None or board[to] in own:
                    continue
                mt = MoveType.CAPTURE if board[to] in enemy else MoveType.QUIET
                moves.append(encode(sq, to, mt))
            moves.extend(_castle_moves(position, color))
        elif piece in (bishop_char, rook_char, queen_char):
            dirs = DIAG4 if piece == bishop_char else ORTHO4 if piece == rook_char else KING8
            for dr, df in dirs:
                rr, ff = (r + dr, f + df)
                while True:
                    to = rf_sq(rr, ff)
                    if to is None or board[to] in own:
                        break
                    if board[to] in enemy:
                        moves.append(encode(sq, to, MoveType.CAPTURE))
                        break
                    moves.append(encode(sq, to, MoveType.QUIET))
                    rr += dr
                    ff += df
    return moves

def _castle_moves(position: Position, color: str) -> list[int]:
    """Structural pseudo-legality only (rights, empty path, rook present).
    Check-safety conditions (spec 3.3 items 3-5) are applied in legal.py."""
    board = position.board
    moves = []
    if color == 'w':
        king_sq, rank = (4, 0)
        k_right, q_right = ('K', 'Q')
        rook_k, rook_q = (7, 0)
        king_char, rook_char = ('K', 'R')
    else:
        king_sq, rank = (60, 7)
        k_right, q_right = ('k', 'q')
        rook_k, rook_q = (63, 56)
        king_char, rook_char = ('k', 'r')
    if board[king_sq] != king_char:
        return moves
    if k_right in position.castling and board[rook_k] == rook_char:
        f1, f2 = (rf_sq(rank, 5), rf_sq(rank, 6))
        if board[f1] == EMPTY and board[f2] == EMPTY:
            moves.append(encode(king_sq, rf_sq(rank, 6), MoveType.KING_CASTLE))
    if q_right in position.castling and board[rook_q] == rook_char:
        f1, f2, f3 = (rf_sq(rank, 1), rf_sq(rank, 2), rf_sq(rank, 3))
        if board[f1] == EMPTY and board[f2] == EMPTY and (board[f3] == EMPTY):
            moves.append(encode(king_sq, rf_sq(rank, 2), MoveType.QUEEN_CASTLE))
    return moves


# ==== engine/checkers_gen.py ====
"""Pseudo-legal checkers move generation: steps, jumps, chains. Spec section 3.2."""
DIAG4 = [(1, 1), (1, -1), (-1, 1), (-1, -1)]
MAN_FORWARD = [(-1, 1), (-1, -1)]

def _checker_steps_from(position: Position, sq: int) -> list[int]:
    piece = position.board[sq]
    is_king = piece == 'C'
    dirs = DIAG4 if is_king else MAN_FORWARD
    r0, f0 = sq_rf(sq)
    results = []
    if is_king and position.config.flying_kings:
        for dr, df in dirs:
            r, f = (r0 + dr, f0 + df)
            while True:
                to = rf_sq(r, f)
                if to is None or position.board[to] != EMPTY:
                    break
                results.append(to)
                r += dr
                f += df
    else:
        for dr, df in dirs:
            to = rf_sq(r0 + dr, f0 + df)
            if to is not None and position.board[to] == EMPTY:
                results.append(to)
    return results

def pseudo_legal_checker_moves(position: Position) -> tuple[list[int], list[int]]:
    """Returns (steps, jumps) as packed moves, ignoring mandatory/maximal capture rules."""
    steps: list[int] = []
    jumps: list[int] = []
    board = position.board
    for sq in range(64):
        if board[sq] not in ('c', 'C'):
            continue
        for to in _checker_steps_from(position, sq):
            steps.append(encode(sq, to, MoveType.CHECKER_STEP))
        for _mid, land in position._checker_jumps_from(sq):
            jumps.append(encode(sq, land, MoveType.CHECKER_JUMP))
    return (steps, jumps)

def _chain_length(position: Position, mv: int) -> int:
    """Total captures achievable by playing mv and then continuing optimally (recursive lookahead)."""
    _frm, to, _mt = decode(mv)
    undo = position.make(mv)
    if position.jump_from == to:
        further = [encode(to, land, MoveType.CHECKER_JUMP) for _m, land in position._checker_jumps_from(to)]
        best = max((_chain_length(position, j) for j in further), default=0)
        total = 1 + best
    else:
        total = 1
    position.unmake(undo)
    return total

def legal_checker_moves(position: Position) -> list[int]:
    """Applies jump-continuation lock, mandatory capture, and maximal capture (spec 3.2)."""
    if position.jump_from is not None:
        sq = position.jump_from
        return [encode(sq, land, MoveType.CHECKER_JUMP) for _m, land in position._checker_jumps_from(sq)]
    steps, jumps = pseudo_legal_checker_moves(position)
    if not jumps:
        return steps
    if not position.config.mandatory_capture:
        return steps + jumps
    if position.config.maximal_capture:
        lengths = [_chain_length(position, mv) for mv in jumps]
        best = max(lengths)
        return [mv for mv, length in zip(jumps, lengths) if length == best]
    return jumps


# ==== engine/legal.py ====
"""Legality filter. Spec section 3.5 and the Correctness Traps of 3.6.

The chess side's legality is determined purely by make-the-move / check-attack /
unmake-the-move. No pins, no discovered-check special casing: they all fall out
of evaluating attacks strictly *after* the candidate move (Trap 1, Trap 2).
"""

def _find_king(board: list[str], king_char: str):
    for sq, ch in enumerate(board):
        if ch == king_char:
            return sq
    return None

def _square_attacked(position: Position, sq: int, own_color: str) -> bool:
    if position.mode == 'chess_only':
        return is_square_attacked_by_chess(position, sq, by_white=own_color == 'b')
    return is_attacked_by_checkers(position, sq)

def _castle_pre_checks(position: Position, color: str, mtype: MoveType) -> bool:
    """Spec 3.3 conditions 3 & 4: not currently in check, doesn't pass through an
    attacked square. Condition 5 (landing square attacked) falls out of the
    generic post-make filter applied to every pseudo-legal move."""
    king_sq = 4 if color == 'w' else 60
    if _square_attacked(position, king_sq, color):
        return False
    rank = king_sq // 8
    pass_file = 5 if mtype == MoveType.KING_CASTLE else 3
    pass_sq = rf_sq(rank, pass_file)
    king_char = position.board[king_sq]
    position.board[king_sq] = EMPTY
    position.board[pass_sq] = king_char
    attacked = _square_attacked(position, pass_sq, color)
    position.board[pass_sq] = EMPTY
    position.board[king_sq] = king_char
    return not attacked

def legal_moves(position: Position) -> list[int]:
    """All legal moves for the side to move (spec 3.5): checkers dispatch to
    checkers_gen; chess moves are pseudo-legal-generated then filtered by
    make/attack/unmake, which handles pins, discovered checks, and Traps 1-4
    (spec 3.6) without any special-casing."""
    if position.side_to_move == Side.CHECKERS and position.mode == 'hybrid':
        return legal_checker_moves(position)
    color = 'w' if position.side_to_move == Side.CHESS else 'b'
    king_char = 'K' if color == 'w' else 'k'
    pseudo = pseudo_legal_chess_moves(position, color)
    if position.mode == 'hybrid' and (not position.config.king_capture_immunity):
        return pseudo
    legal = []
    for mv in pseudo:
        _frm, _to, mtype = decode(mv)
        if mtype in (MoveType.KING_CASTLE, MoveType.QUEEN_CASTLE):
            if not _castle_pre_checks(position, color, mtype):
                continue
        undo = position.make(mv)
        king_sq = _find_king(position.board, king_char)
        safe = king_sq is None or not _square_attacked(position, king_sq, color)
        position.unmake(undo)
        if safe:
            legal.append(mv)
    return legal

def in_check(position: Position) -> bool:
    """Is the chess king (of the side to move, chess-only mode aware) currently attacked?"""
    color = 'w' if position.side_to_move == Side.CHESS else 'b'
    if position.mode == 'hybrid' and position.side_to_move != Side.CHESS:
        return False
    king_char = 'K' if color == 'w' else 'k'
    king_sq = _find_king(position.board, king_char)
    if king_sq is None:
        return False
    return _square_attacked(position, king_sq, color)


# ==== engine/terminal.py ====
"""Win/draw detection. Spec section 5. Order of evaluation matters (5, table)."""

def result(position: Position) -> Result | None:
    """None if the game continues. Evaluated in the order given in spec section 5."""
    if position.mode != 'hybrid':
        return _chess_only_result(position)
    if not position.config.king_capture_immunity and 'K' not in position.board:
        return Result.CHECKERS_WIN
    checkers_left = sum((1 for ch in position.board if ch in ('c', 'C')))
    if checkers_left == 0:
        return Result.CHESS_WIN
    if position.side_to_move == Side.CHECKERS:
        if not legal_moves(position):
            return Result.CHESS_WIN
    elif not legal_moves(position):
        return Result.CHECKERS_WIN
    if position.repetition_count() >= 3:
        return Result.DRAW
    if position.halfmove_clock >= position.config.fifty_move_plies:
        return Result.DRAW
    return None

def _chess_only_result(position: Position) -> Result | None:
    """Plain chess terminal detection, used only by the perft/differential test mode."""
    if not legal_moves(position):
        if in_check(position):
            return Result.CHECKERS_WIN if position.side_to_move == Side.CHESS else Result.CHESS_WIN
        return Result.DRAW
    if position.repetition_count() >= 3:
        return Result.DRAW
    if position.halfmove_clock >= position.config.fifty_move_plies:
        return Result.DRAW
    return None


# ==== engine/serialize.py ====
"""State string read/write and human-readable move notation. Spec section 7.5."""

def serialize(position: Position) -> str:
    """Position -> the FEN-like state string of spec 7.5. Round-trips exactly with deserialize()."""
    rows = []
    for r in range(7, -1, -1):
        row = ''
        empty_count = 0
        for f in range(8):
            ch = position.board[r * 8 + f]
            if ch == EMPTY:
                empty_count += 1
            else:
                if empty_count:
                    row += str(empty_count)
                    empty_count = 0
                row += ch
        if empty_count:
            row += str(empty_count)
        rows.append(row)
    board_str = '|'.join(rows)
    side = 'w' if position.side_to_move == Side.CHESS else 'b'
    castling = ''.join((c for c in 'KQ' if c in position.castling)) or '-'
    ep = square_name(position.ep_square) if position.ep_square is not None else '-'
    jf = square_name(position.jump_from) if position.jump_from is not None else '-'
    return '/'.join([board_str, side, castling, ep, str(position.halfmove_clock), str(position.fullmove_number), jf, position.config.config_hash()])

def deserialize(state: str, config: RuleConfig) -> Position:
    """State string -> Position. Raises ValueError on malformed input or a
    config-hash mismatch (spec 7.5: never silently proceed on a mismatch)."""
    parts = state.split('/')
    if len(parts) != 8:
        raise ValueError(f'malformed state string: expected 8 fields, got {len(parts)}')
    board_str, side, castling, ep, halfmove, fullmove, jf, cfg_hash = parts
    if cfg_hash != config.config_hash():
        raise ValueError('state was serialized under a different RuleConfig')
    board = [EMPTY] * 64
    rows = board_str.split('|')
    if len(rows) != 8:
        raise ValueError('malformed state string: expected 8 ranks')
    for i, row in enumerate(rows):
        r = 7 - i
        f = 0
        for ch in row:
            if ch.isdigit():
                f += int(ch)
            else:
                if f > 7:
                    raise ValueError('malformed state string: rank overflow')
                board[rf_sq(r, f)] = ch
                f += 1
    pos = Position.__new__(Position)
    pos.config = config
    pos.mode = 'hybrid'
    pos.board = board
    pos.chess_color = 'w'
    pos.castling = set((c for c in castling if c in 'KQ'))
    pos.side_to_move = Side.CHESS if side == 'w' else Side.CHECKERS
    pos.ep_square = square_from_name(ep) if ep != '-' else None
    pos.halfmove_clock = int(halfmove)
    pos.fullmove_number = int(fullmove)
    pos.jump_from = square_from_name(jf) if jf != '-' else None
    pos.history = []
    pos._key = pos._compute_key()
    pos.history.append(pos._key)
    return pos

def move_to_str(position: Position, mv: int) -> str:
    """SAN-ish notation: piece letter (chess only) + from + capture marker + to + promotion."""
    frm, to, mtype = decode(mv)
    piece = position.board[frm]
    is_capture = position.board[to] != EMPTY or mtype in (MoveType.EP_CAPTURE, MoveType.CHECKER_JUMP)
    if mtype == MoveType.KING_CASTLE:
        return 'O-O'
    if mtype == MoveType.QUEEN_CASTLE:
        return 'O-O-O'
    prefix = piece.upper() if piece.upper() not in ('P', 'C') else ''
    sep = 'x' if is_capture else '-'
    s = f'{prefix}{square_name(frm)}{sep}{square_name(to)}'
    if mtype in PROMO_PIECE:
        s += f'={PROMO_PIECE[mtype]}'
    return s


# ==== engine/planes.py ====
"""to_planes(): NN input tensor. Spec section 7.6. Unused by anything today;
built now so the future training phase has a stable interface to target."""
CHESS_PIECE_ORDER = 'PNBRQK'
MOBILITY_PIECE_ORDER = 'PNBRQKcC'
NUM_PLANES = 21 + len(MOBILITY_PIECE_ORDER)

def to_planes(position: Position, legal=None) -> np.ndarray:
    """Position -> (NUM_PLANES, 8, 8) float32 NN input tensor (spec 7.6).
    `legal` is the side-to-move's legal_moves() list, if the caller already
    has one (e.g. mid self-play) — pass it in to skip recomputing it here
    for the mobility planes. Left None, to_planes computes its own."""
    planes = np.zeros((NUM_PLANES, 8, 8), dtype=np.float32)
    idx = 0
    for piece_char in CHESS_PIECE_ORDER:
        for sq, ch in enumerate(position.board):
            if ch == piece_char:
                r, f = sq_rf(sq)
                planes[idx, r, f] = 1.0
        idx += 1
    for piece_char in ('c', 'C'):
        for sq, ch in enumerate(position.board):
            if ch == piece_char:
                r, f = sq_rf(sq)
                planes[idx, r, f] = 1.0
        idx += 1
    for r in range(8):
        for f in range(8):
            planes[idx, r, f] = 1.0 if (r + f) % 2 == 1 else 0.0
    idx += 1
    for right in ('K', 'Q', 'k', 'q'):
        planes[idx, :, :] = 1.0 if right in position.castling else 0.0
        idx += 1
    if position.ep_square is not None:
        r, f = sq_rf(position.ep_square)
        planes[idx, r, f] = 1.0
    idx += 1
    planes[idx, :, :] = 1.0 if position.side_to_move == Side.CHECKERS else 0.0
    idx += 1
    if position.jump_from is not None:
        r, f = sq_rf(position.jump_from)
        planes[idx, r, f] = 1.0
    idx += 1
    planes[idx, :, :] = min(position.halfmove_clock / position.config.fifty_move_plies, 1.0)
    idx += 1
    rep = position.repetition_count()
    planes[idx, :, :] = 1.0 if rep >= 2 else 0.0
    idx += 1
    planes[idx, :, :] = 1.0 if rep >= 3 else 0.0
    idx += 1
    king_sq = None
    for sq, ch in enumerate(position.board):
        if ch == 'K':
            king_sq = sq
            break
    threats = checkers_attacking(position, king_sq) if king_sq is not None else []
    planes[idx, :, :] = 1.0 if threats else 0.0
    idx += 1
    for s in threats:
        r, f = sq_rf(s)
        planes[idx, r, f] = 1.0
    idx += 1
    if legal is None:
        legal = _legal_moves(position)
    mobility_idx = {ch: idx + i for i, ch in enumerate(MOBILITY_PIECE_ORDER)}
    for mv in legal:
        frm, to, _mtype = decode(mv)
        plane = mobility_idx.get(position.board[frm])
        if plane is not None:
            r, f = sq_rf(to)
            planes[plane, r, f] = 1.0
    idx += len(MOBILITY_PIECE_ORDER)
    assert idx == NUM_PLANES
    return planes


# ==== training loop ====
NUM_MOVE_TYPES = len(MoveType)

class ResidualBlock(nn.Module):
    """Standard AlphaZero-style residual block. GroupNorm, not BatchNorm —
    self-play forwards one position at a time (batch size 1), where BatchNorm's
    per-batch statistics are noisy/unstable; GroupNorm normalizes within a
    single example and doesn't have that failure mode."""

    def __init__(self, channels: int, groups: int=8):
        super().__init__()
        self.conv1 = nn.Conv2d(channels, channels, kernel_size=3, padding=1)
        self.norm1 = nn.GroupNorm(groups, channels)
        self.conv2 = nn.Conv2d(channels, channels, kernel_size=3, padding=1)
        self.norm2 = nn.GroupNorm(groups, channels)

    def forward(self, x):
        residual = x
        out = F.relu(self.norm1(self.conv1(x)))
        out = self.norm2(self.conv2(out))
        return F.relu(out + residual)

class PolicyValueNet(nn.Module):
    """channels/num_blocks are deliberately parameters, not constants — checkers'
    task (build a mating net from one-square diagonal steps) is harder than
    chess' (capture everything), so checkers_net is given more capacity than
    chess_net (see train(), where the two are constructed) rather than treating
    the two sides as symmetric by default."""

    def __init__(self, in_channels: int=NUM_PLANES, channels: int=64, num_blocks: int=6):
        super().__init__()
        self.stem = nn.Sequential(nn.Conv2d(in_channels, channels, kernel_size=3, padding=1), nn.GroupNorm(8, channels), nn.ReLU(inplace=True))
        self.tower = nn.Sequential(*[ResidualBlock(channels) for _ in range(num_blocks)])
        flat = channels * 8 * 8
        self.from_head = nn.Linear(flat, 64)
        self.to_head = nn.Linear(flat, 64)
        self.type_head = nn.Linear(flat, NUM_MOVE_TYPES)
        self.value_head = nn.Sequential(nn.Linear(flat, 128), nn.ReLU(inplace=True), nn.Linear(128, 1), nn.Tanh())

    def forward(self, planes):
        x = self.stem(planes)
        x = self.tower(x)
        x = x.flatten(1)
        value = self.value_head(x).squeeze(-1)
        return (self.from_head(x), self.to_head(x), self.type_head(x), value)

def move_scores(from_logits, to_logits, type_logits, legal_moves):
    frms, tos, mtypes = zip(*(decode(mv) for mv in legal_moves))
    device = from_logits.device
    frms = torch.tensor(frms, dtype=torch.long, device=device)
    tos = torch.tensor(tos, dtype=torch.long, device=device)
    mtypes = torch.tensor([int(t) for t in mtypes], dtype=torch.long, device=device)
    return from_logits[frms] + to_logits[tos] + type_logits[mtypes]
DIRICHLET_ALPHA = 0.3
NOISE_EPS = 0.1

def select_move(net, planes, legal_moves, device):
    x = torch.from_numpy(planes).unsqueeze(0).to(device)
    from_logits, to_logits, type_logits, value = net(x)
    scores = move_scores(from_logits[0], to_logits[0], type_logits[0], legal_moves)
    net_probs = F.softmax(scores, dim=-1)
    noise = torch.distributions.Dirichlet(torch.full((len(legal_moves),), DIRICHLET_ALPHA, device=device)).sample()
    mixed_probs = (1.0 - NOISE_EPS) * net_probs + NOISE_EPS * noise
    dist = torch.distributions.Categorical(probs=mixed_probs)
    idx = dist.sample()
    return (legal_moves[idx.item()], dist.log_prob(idx), value[0], dist.entropy())
WIN_BONUS = 150.0
CHESS_PIECE_VALUE = {'P': 1, 'N': 3, 'B': 3, 'R': 5, 'Q': 9}
CHESS_NORMAL_DRAW_BONUS = 12.0
CHECKERS_NORMAL_DRAW_BONUS = 20.0
CHESS_WORST_PENALTY = 5.0
CHECKERS_WORST_PENALTY = 8.0
CHESS_KING_CAPTURED_PENALTY = 10.0
ENTROPY_COEF = 0.05
REPETITION_STEP_PENALTY = 0.02

def _material_snapshot(board):
    """(count of checker pieces, total value of chess pieces) currently on the board."""
    checker_count = 0
    chess_value = 0
    for ch in board:
        if ch in ('c', 'C'):
            checker_count += 1
        elif ch in CHESS_PIECE_VALUE:
            chess_value += CHESS_PIECE_VALUE[ch]
    return (checker_count, chess_value)

def reward_for(side, result, checkers_captured_by_chess, chess_value_captured_by_checkers, is_repetition_draw, chess_king_captured=False):
    """Four tiers, best to worst: WIN (flat WIN_BONUS) > fifty-move-rule draw
    (material + a BONUS, deliberately better than a same-material loss) >
    loss (material only, floor 0) ≈ threefold-repetition draw / ply-cap
    unresolved (material - a small flat penalty, floored at 0 same as a
    loss — see CHESS_NORMAL_DRAW_BONUS / CHESS_WORST_PENALTY comment block
    for why this tier used to be forced deeply negative and isn't anymore).
    chess_king_captured further splits the loss tier: a CHECKERS_WIN caused
    by the king actually being captured scores below one caused by chess
    just running out of moves (see CHESS_KING_CAPTURED_PENALTY) — also
    floored at 0."""
    if side == Side.CHESS:
        if result == Result.CHESS_WIN:
            return WIN_BONUS
        points = float(checkers_captured_by_chess)
        if result == Result.CHECKERS_WIN and chess_king_captured:
            points = max(0.0, points - CHESS_KING_CAPTURED_PENALTY)
        if result == Result.DRAW:
            points = points + CHESS_NORMAL_DRAW_BONUS if not is_repetition_draw else max(0.0, points - CHESS_WORST_PENALTY)
        elif result is None:
            points = max(0.0, points - CHESS_WORST_PENALTY)
        return points
    else:
        if result == Result.CHECKERS_WIN:
            return WIN_BONUS
        points = float(chess_value_captured_by_checkers)
        if result == Result.DRAW:
            points = points + CHECKERS_NORMAL_DRAW_BONUS if not is_repetition_draw else max(0.0, points - CHECKERS_WORST_PENALTY)
        elif result is None:
            points = max(0.0, points - CHECKERS_WORST_PENALTY)
        return points

def _ban_repetition_moves(pos, legal_moves, seen_counts):
    """Removes any move that would trigger the 3rd occurrence of a position
    (the move that causes a threefold-repetition draw) from the legal set —
    but only when at least one other legal move avoids it. Never bans down
    to zero moves: doing so would hand the opponent an artificial "no legal
    move" win/loss (see terminal.py) unrelated to actual play, converting a
    training-time nudge into a rules-engine exploit. Training-only — this
    filter is never applied to the deployed game, which still allows
    repetition draws normally; RuleConfig itself is untouched.

    Previously tried and reverted (see git history / conversation): banning
    outright, with a policy still this early in training, produced ~95%
    ply-cap-unresolved games instead of more wins — no reward tuning fixes
    that on its own. Reintroduced now paired with CHESS/CHECKERS_WORST_PENALTY
    treating unresolved the same as a threefold draw (both the worst tier),
    so at minimum there's real pressure against the failure mode this caused
    last time, not just against repetition specifically.

    `seen_counts` is a dict mirroring pos.history's key counts, maintained by
    the caller — pos.repetition_count() itself does an O(n) scan of the whole
    game history per call, and this function needs one such check per legal
    move, per ply; on a long game that's O(n * branching) per ply and made
    real self-play runs time out. An external O(1) dict lookup avoids that
    without changing the check's meaning at all."""
    non_repeating = []
    for mv in legal_moves:
        undo = pos.make(mv)
        would_repeat = seen_counts.get(pos._key, 0) + 1 >= 3
        pos.unmake(undo)
        if not would_repeat:
            non_repeating.append(mv)
    return non_repeating if non_repeating else legal_moves

def self_play_game(chess_net, checkers_net, config, device, max_plies=800):
    pos = Position(config)
    first_mover = pos.side_to_move
    traj = {Side.CHESS: [], Side.CHECKERS: []}
    plies = 0
    seen_counts = {pos._key: 1}
    checkers_captured_by_chess = 0
    chess_value_captured_by_checkers = 0
    prev_checker_count, prev_chess_value = _material_snapshot(pos.board)
    while pos.result() is None and plies < max_plies:
        side = pos.side_to_move
        net = chess_net if side == Side.CHESS else checkers_net
        legal = pos.legal_moves()
        if not legal:
            break
        legal = _ban_repetition_moves(pos, legal, seen_counts)
        mv, log_prob, value, entropy = select_move(net, pos.to_planes(legal=legal), legal, device)
        pos.make(mv)
        plies += 1
        seen_counts[pos._key] = seen_counts.get(pos._key, 0) + 1
        step_reward = -REPETITION_STEP_PENALTY if seen_counts[pos._key] >= 2 else 0.0
        traj[side].append((log_prob, value, entropy, step_reward))
        checker_count, chess_value = _material_snapshot(pos.board)
        if side == Side.CHESS and checker_count < prev_checker_count:
            checkers_captured_by_chess += prev_checker_count - checker_count
        elif side == Side.CHECKERS and chess_value < prev_chess_value:
            chess_value_captured_by_checkers += prev_chess_value - chess_value
        prev_checker_count, prev_chess_value = (checker_count, chess_value)
    return (pos.result(), traj, plies, pos, first_mover, checkers_captured_by_chess, chess_value_captured_by_checkers)

def explain_result(pos, plies, max_plies=800):
    """Human-readable reason the game ended, cross-checked against the
    engine's own terminal rules — not just the win/loss/draw label."""
    result = pos.result()
    checkers_left = sum((1 for ch in pos.board if ch in ('c', 'C')))
    if result is None:
        return f'did NOT terminate within {max_plies} plies (hit the ply cap, counted as unterminated)'
    if result == Result.CHESS_WIN:
        if checkers_left == 0:
            return 'all checker pieces captured -> chess wins'
        return 'checkers side to move had no legal move -> chess wins'
    if result == Result.CHECKERS_WIN:
        if 'K' not in pos.board:
            return 'chess king captured (king_capture_immunity=False) -> checkers wins'
        return 'chess side to move had no legal move (checkmate or stalemate) -> checkers wins'
    if result == Result.DRAW:
        if pos.repetition_count() >= 3:
            return 'threefold repetition -> draw'
        if pos.halfmove_clock >= pos.config.fifty_move_plies:
            return 'fifty-move rule -> draw'
        return "draw (unspecified — shouldn't happen; investigate)"
    return f'unrecognized result value: {result!r}'

def render_board(pos):
    lines = []
    for r in range(7, -1, -1):
        lines.append(' '.join((pos.board[r * 8 + f] for f in range(8))))
    return '\n'.join(lines)

def atomic_save(net, games_trained, path):
    tmp = path + '.tmp'
    torch.save({'model_state_dict': net.state_dict(), 'games_trained': games_trained}, tmp)
    os.replace(tmp, path)

def load_if_exists(net, path, device):
    """Returns the cumulative games_trained count stored in the checkpoint, or 0 if none."""
    if not os.path.exists(path):
        return 0
    payload = torch.load(path, map_location=device)
    if isinstance(payload, dict) and 'model_state_dict' in payload:
        net.load_state_dict(payload['model_state_dict'])
        return payload.get('games_trained', 0)
    net.load_state_dict(payload)
    return 0
LOG_FIELDS = ['game', 'timestamp', 'first_mover', 'winner', 'plies', 'seconds', 'chess_points', 'checkers_points', 'reason']

def append_log(log_path, rows):
    """Appends game records to a persistent CSV, one row per game, across every
    run/session — not just this run's terminal output, which disappears."""
    is_new = not os.path.exists(log_path)
    with open(log_path, 'a', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=LOG_FIELDS)
        if is_new:
            writer.writeheader()
        writer.writerows(rows)

def status_line(cumulative, total_target, plies, dt, tally):
    return f'\r[{cumulative}/{total_target}] plies={plies} {dt:.1f}s/game tally={tally}          '

def train(n_games, config, gamma, lr, device, checkpoint_every, log_every, chess_path, checkers_path, log_path, log_enabled=True, seed=None, batch_size=5, freeze_chess=False):
    if seed is not None:
        random.seed(seed)
        torch.manual_seed(seed)
    chess_net = PolicyValueNet(channels=128, num_blocks=10).to(device)
    checkers_net = PolicyValueNet(channels=160, num_blocks=13).to(device)
    games_before = load_if_exists(chess_net, chess_path, device)
    load_if_exists(checkers_net, checkers_path, device)
    if games_before:
        print(f'resuming: {games_before} games already trained, continuing to {games_before + n_games}')
    chess_opt = torch.optim.Adam(chess_net.parameters(), lr=lr)
    checkers_opt = torch.optim.Adam(checkers_net.parameters(), lr=lr)
    chess_opt.zero_grad()
    checkers_opt.zero_grad()
    tally = {'chess': 0, 'checkers': 0, 'draw': 0, 'unterminated': 0}
    result_name = {Result.CHESS_WIN: 'chess', Result.CHECKERS_WIN: 'checkers', Result.DRAW: 'draw'}
    total_target = games_before + n_games
    side_name = {Side.CHESS: 'chess', Side.CHECKERS: 'checkers'}
    game_log = []
    last_pos = None
    for i in range(n_games):
        t0 = time.monotonic()
        result, traj, plies, last_pos, first_mover, checkers_captured, chess_value_captured = self_play_game(chess_net, checkers_net, config, device)
        dt = time.monotonic() - t0
        tally[result_name.get(result, 'unterminated')] += 1
        cumulative = games_before + i + 1
        is_repetition_draw = result == Result.DRAW and last_pos.repetition_count() >= 3
        chess_king_captured = result == Result.CHECKERS_WIN and 'K' not in last_pos.board
        chess_points = reward_for(Side.CHESS, result, checkers_captured, chess_value_captured, is_repetition_draw, chess_king_captured)
        checkers_points = reward_for(Side.CHECKERS, result, checkers_captured, chess_value_captured, is_repetition_draw)
        game_log.append({'game': cumulative, 'timestamp': datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds'), 'first_mover': side_name[first_mover], 'winner': result_name.get(result, 'unterminated'), 'plies': plies, 'seconds': round(dt, 1), 'chess_points': chess_points, 'checkers_points': checkers_points, 'reason': explain_result(last_pos, plies)})
        for side, points in ((Side.CHESS, chess_points), (Side.CHECKERS, checkers_points)):
            if freeze_chess and side == Side.CHESS:
                continue
            entries = traj[side]
            n = len(entries)
            if n == 0:
                continue
            r = points / WIN_BONUS
            step_rewards = [sr for _lp, _v, _e, sr in entries]
            step_rewards[-1] += r
            returns_list = [0.0] * n
            running = 0.0
            for t in range(n - 1, -1, -1):
                running = step_rewards[t] + gamma * running
                returns_list[t] = running
            returns = torch.tensor(returns_list, device=device)
            log_probs = torch.stack([lp for lp, _v, _e, _sr in entries])
            values = torch.stack([v for _lp, v, _e, _sr in entries])
            entropies = torch.stack([e for _lp, _v, e, _sr in entries])
            advantage = returns - values.detach()
            policy_loss = -(log_probs * advantage).mean()
            value_loss = F.mse_loss(values, returns)
            entropy_loss = -entropies.mean()
            (policy_loss + 0.5 * value_loss + ENTROPY_COEF * entropy_loss).backward()
        if cumulative % batch_size == 0 or i == n_games - 1:
            if not freeze_chess:
                chess_opt.step()
                chess_opt.zero_grad()
            checkers_opt.step()
            checkers_opt.zero_grad()
        if cumulative % checkpoint_every == 0 or i == n_games - 1:
            atomic_save(chess_net, cumulative, chess_path)
            atomic_save(checkers_net, cumulative, checkers_path)
        sys.stdout.write(status_line(cumulative, total_target, plies, dt, tally))
        sys.stdout.flush()
        if cumulative % log_every == 0 or i == n_games - 1:
            print()
    print(f'\ndone. {games_before + n_games} games trained total. final tally this run={tally}')
    if log_enabled:
        append_log(log_path, game_log)
        print(f"logged {len(game_log)} game{('s' if len(game_log) != 1 else '')} to {log_path}")
    else:
        print('logging disabled (--no-log): not writing to training_log.csv')
    breakdown = {'chess_wins': sum((1 for g in game_log if g['winner'] == 'chess')), 'checkers_wins': sum((1 for g in game_log if g['winner'] == 'checkers')), 'draws_threefold_repetition': sum((1 for g in game_log if g['winner'] == 'draw' and 'threefold' in g['reason'])), 'draws_fifty_move_rule': sum((1 for g in game_log if g['winner'] == 'draw' and 'fifty-move' in g['reason'])), 'unterminated': sum((1 for g in game_log if g['winner'] == 'unterminated'))}
    print(f'\nbatch breakdown ({len(game_log)} games this run):')
    print(json.dumps(breakdown, indent=2))
    print(f"\nper-game stats ({len(game_log)} game{('s' if len(game_log) != 1 else '')} this run):")
    header = f"{'game':>5}  {'first mover':<11} {'winner':<11} {'plies':>6}  {'sec':>5}  {'chess pts':>9}  {'checkers pts':>12}  reason"
    print(header)
    print('-' * len(header))
    for g in game_log:
        print(f"{g['game']:>5}  {g['first_mover']:<11} {g['winner']:<11} {g['plies']:>6}  {g['seconds']:>5}  {g['chess_points']:>9.0f}  {g['checkers_points']:>12.0f}  {g['reason']}")
    if last_pos is not None:
        print('\nfinal board of the last game (rank 8 top, a-file left):')
        print(render_board(last_pos))
    return (chess_net, checkers_net)

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--games', type=int, default=100, help='how many MORE games to run this session')
    p.add_argument('--gamma', type=float, default=0.99)
    p.add_argument('--lr', type=float, default=0.001)
    p.add_argument('--batch-size', type=int, default=5, help='games per gradient step (gradients accumulate across the batch); 1 = update every game (old behavior)')
    p.add_argument('--checkpoint-every', type=int, default=1, help='save after every N games; low default trades a little speed for crash safety')
    p.add_argument('--log-every', type=int, default=20, help='how often to leave a permanent log line instead of overwriting in place')
    p.add_argument('--chess-out', default='chess_net.pt')
    p.add_argument('--checkers-out', default='checkers_net.pt')
    p.add_argument('--log-path', default='training_log.csv', help="persistent per-game stats, appended across every run/session — survives after the terminal doesn't")
    p.add_argument('--no-log', action='store_true', help='disable writing to training_log.csv (on by default — cheap, and useful history to have)')
    p.add_argument('--seed', type=int, default=None)
    p.add_argument('--freeze-chess', action='store_true', help='chess_net still plays every game but never updates — checkers keeps learning normally. Manual toggle: rerun without this flag once checkers gets its first win.')
    args = p.parse_args()
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f'device: {device}')
    cfg = RuleConfig()
    print(f"RuleConfig hash: {cfg.config_hash()} — must match the deployed server's /api/config")
    train(n_games=args.games, config=cfg, gamma=args.gamma, lr=args.lr, device=device, checkpoint_every=args.checkpoint_every, log_every=args.log_every, chess_path=args.chess_out, checkers_path=args.checkers_out, log_path=args.log_path, log_enabled=not args.no_log, seed=args.seed, batch_size=args.batch_size, freeze_chess=args.freeze_chess)
if __name__ == '__main__':
    main()
